services:
  service-refeicao-mariadb:
    image: bitnami/mariadb:latest
    container_name: refeicoes-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=refeicoes
      - MARIADB_USER=user
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: unless-stopped

volumes:
  mariadb_data: