services:
  service-clube-esquina-mariadb:
    image: bitnami/mariadb:latest
    container_name: clube-esquina-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=clube_esquina
      - MARIADB_USER=user
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: unless-stopped

volumes:
  mariadb_data: